// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RichMan.proto

package com.lyncc.netty.codec.protobuf.demo;

public final class RichManProto {
    private RichManProto() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface RichManOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netty.RichMan)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 id = 1;</code>
         */
        boolean hasId();

        /**
         * <code>required int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>required string name = 2;</code>
         */
        boolean hasName();

        /**
         * <code>required string name = 2;</code>
         */
        java.lang.String getName();

        /**
         * <code>required string name = 2;</code>
         */
        com.google.protobuf.ByteString getNameBytes();

        /**
         * <code>optional string email = 3;</code>
         */
        boolean hasEmail();

        /**
         * <code>optional string email = 3;</code>
         */
        java.lang.String getEmail();

        /**
         * <code>optional string email = 3;</code>
         */
        com.google.protobuf.ByteString getEmailBytes();

        /**
         * <code>repeated .netty.RichMan.Car cars = 4;</code>
         */
        java.util.List<com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car> getCarsList();

        /**
         * <code>repeated .netty.RichMan.Car cars = 4;</code>
         */
        com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car getCars(int index);

        /**
         * <code>repeated .netty.RichMan.Car cars = 4;</code>
         */
        int getCarsCount();

        /**
         * <code>repeated .netty.RichMan.Car cars = 4;</code>
         */
        java.util.List<? extends com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarOrBuilder> getCarsOrBuilderList();

        /**
         * <code>repeated .netty.RichMan.Car cars = 4;</code>
         */
        com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarOrBuilder getCarsOrBuilder(int index);
    }

    /**
     * Protobuf type {@code netty.RichMan}
     */
    public static final class RichMan extends com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:netty.RichMan)
            RichManOrBuilder {
        // Use RichMan.newBuilder() to construct.
        private RichMan(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private RichMan(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final RichMan defaultInstance;

        public static RichMan getDefaultInstance() {
            return defaultInstance;
        }

        public RichMan getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private RichMan(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                    .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {
                        bitField0_ |= 0x00000001;
                        id_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000002;
                        name_ = bs;
                        break;
                    }
                    case 26: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000004;
                        email_ = bs;
                        break;
                    }
                    case 34: {
                        if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                            cars_ = new java.util.ArrayList<com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car>();
                            mutable_bitField0_ |= 0x00000008;
                        }
                        cars_.add(input.readMessage(
                                com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.PARSER, extensionRegistry));
                        break;
                    }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                    cars_ = java.util.Collections.unmodifiableList(cars_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.lyncc.netty.codec.protobuf.demo.RichManProto.internal_static_netty_RichMan_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.lyncc.netty.codec.protobuf.demo.RichManProto.internal_static_netty_RichMan_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.class,
                            com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Builder.class);
        }

        public static com.google.protobuf.Parser<RichMan> PARSER = new com.google.protobuf.AbstractParser<RichMan>() {
            public RichMan parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new RichMan(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<RichMan> getParserForType() {
            return PARSER;
        }

        /**
         * Protobuf enum {@code netty.RichMan.CarType}
         */
        public enum CarType implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>AUDI = 0;</code>
             */
            AUDI(0, 0),
            /**
             * <code>BENZ = 1;</code>
             */
            BENZ(1, 1),
            /**
             * <code>LAMBORGHINI = 2;</code>
             */
            LAMBORGHINI(2, 2),
            /**
             * <code>DASAUTO = 3;</code>
             */
            DASAUTO(3, 3), ;

            /**
             * <code>AUDI = 0;</code>
             */
            public static final int AUDI_VALUE = 0;

            /**
             * <code>BENZ = 1;</code>
             */
            public static final int BENZ_VALUE = 1;

            /**
             * <code>LAMBORGHINI = 2;</code>
             */
            public static final int LAMBORGHINI_VALUE = 2;

            /**
             * <code>DASAUTO = 3;</code>
             */
            public static final int DASAUTO_VALUE = 3;

            public final int getNumber() {
                return value;
            }

            public static CarType valueOf(int value) {
                switch (value) {
                case 0:
                    return AUDI;
                case 1:
                    return BENZ;
                case 2:
                    return LAMBORGHINI;
                case 3:
                    return DASAUTO;
                default:
                    return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<CarType> internalGetValueMap() {
                return internalValueMap;
            }

            private static com.google.protobuf.Internal.EnumLiteMap<CarType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<CarType>() {
                public CarType findValueByNumber(int number) {
                    return CarType.valueOf(number);
                }
            };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
                return getDescriptor().getValues().get(index);
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
                return getDescriptor();
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
                return com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.getDescriptor().getEnumTypes().get(0);
            }

            private static final CarType[] VALUES = values();

            public static CarType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            private final int index;

            private final int value;

            private CarType(int index, int value) {
                this.index = index;
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:netty.RichMan.CarType)
        }

        public interface CarOrBuilder extends
        // @@protoc_insertion_point(interface_extends:netty.RichMan.Car)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>required string name = 1;</code>
             */
            boolean hasName();

            /**
             * <code>required string name = 1;</code>
             */
            java.lang.String getName();

            /**
             * <code>required string name = 1;</code>
             */
            com.google.protobuf.ByteString getNameBytes();

            /**
             * <code>optional .netty.RichMan.CarType type = 2 [default = BENZ];</code>
             */
            boolean hasType();

            /**
             * <code>optional .netty.RichMan.CarType type = 2 [default = BENZ];</code>
             */
            com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType getType();
        }

        /**
         * Protobuf type {@code netty.RichMan.Car}
         */
        public static final class Car extends com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:netty.RichMan.Car)
                CarOrBuilder {
            // Use Car.newBuilder() to construct.
            private Car(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
                super(builder);
                this.unknownFields = builder.getUnknownFields();
            }

            private Car(boolean noInit) {
                this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
            }

            private static final Car defaultInstance;

            public static Car getDefaultInstance() {
                return defaultInstance;
            }

            public Car getDefaultInstanceForType() {
                return defaultInstance;
            }

            private final com.google.protobuf.UnknownFieldSet unknownFields;

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
                return this.unknownFields;
            }

            private Car(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                initFields();
                int mutable_bitField0_ = 0;
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                        .newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            name_ = bs;
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();
                            com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType value = com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType
                                    .valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(2, rawValue);
                            } else {
                                bitField0_ |= 0x00000002;
                                type_ = value;
                            }
                            break;
                        }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                            .setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.lyncc.netty.codec.protobuf.demo.RichManProto.internal_static_netty_RichMan_Car_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.lyncc.netty.codec.protobuf.demo.RichManProto.internal_static_netty_RichMan_Car_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.class,
                                com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder.class);
            }

            public static com.google.protobuf.Parser<Car> PARSER = new com.google.protobuf.AbstractParser<Car>() {
                public Car parsePartialFrom(com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new Car(input, extensionRegistry);
                }
            };

            @java.lang.Override
            public com.google.protobuf.Parser<Car> getParserForType() {
                return PARSER;
            }

            private int bitField0_;

            public static final int NAME_FIELD_NUMBER = 1;

            private java.lang.Object name_;

            /**
             * <code>required string name = 1;</code>
             */
            public boolean hasName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string name = 1;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        name_ = s;
                    }
                    return s;
                }
            }

            /**
             * <code>required string name = 1;</code>
             */
            public com.google.protobuf.ByteString getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            public static final int TYPE_FIELD_NUMBER = 2;

            private com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType type_;

            /**
             * <code>optional .netty.RichMan.CarType type = 2 [default = BENZ];</code>
             */
            public boolean hasType() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional .netty.RichMan.CarType type = 2 [default = BENZ];</code>
             */
            public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType getType() {
                return type_;
            }

            private void initFields() {
                name_ = "";
                type_ = com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType.BENZ;
            }

            private byte memoizedIsInitialized = -1;

            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1)
                    return true;
                if (isInitialized == 0)
                    return false;

                if (!hasName()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
                memoizedIsInitialized = 1;
                return true;
            }

            public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
                getSerializedSize();
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    output.writeBytes(1, getNameBytes());
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    output.writeEnum(2, type_.getNumber());
                }
                getUnknownFields().writeTo(output);
            }

            private int memoizedSerializedSize = -1;

            public int getSerializedSize() {
                int size = memoizedSerializedSize;
                if (size != -1)
                    return size;

                size = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getNameBytes());
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    size += com.google.protobuf.CodedOutputStream.computeEnumSize(2, type_.getNumber());
                }
                size += getUnknownFields().getSerializedSize();
                memoizedSerializedSize = size;
                return size;
            }

            private static final long serialVersionUID = 0L;

            @java.lang.Override
            protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
                return super.writeReplace();
            }

            public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car parseFrom(
                    com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car parseFrom(
                    com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car parseFrom(byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car parseFrom(
                    java.io.InputStream input) throws java.io.IOException {
                return PARSER.parseFrom(input);
            }

            public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car parseFrom(
                    java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }

            public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car parseDelimitedFrom(
                    java.io.InputStream input) throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input);
            }

            public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car parseDelimitedFrom(
                    java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input, extensionRegistry);
            }

            public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car parseFrom(
                    com.google.protobuf.CodedInputStream input) throws java.io.IOException {
                return PARSER.parseFrom(input);
            }

            public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }

            public static Builder newBuilder() {
                return Builder.create();
            }

            public Builder newBuilderForType() {
                return newBuilder();
            }

            public static Builder newBuilder(com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car prototype) {
                return newBuilder().mergeFrom(prototype);
            }

            public Builder toBuilder() {
                return newBuilder(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            /**
             * Protobuf type {@code netty.RichMan.Car}
             */
            public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:netty.RichMan.Car)
                    com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                    return com.lyncc.netty.codec.protobuf.demo.RichManProto.internal_static_netty_RichMan_Car_descriptor;
                }

                protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                    return com.lyncc.netty.codec.protobuf.demo.RichManProto.internal_static_netty_RichMan_Car_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.class,
                                    com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder.class);
                }

                // Construct using
                // com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    }
                }

                private static Builder create() {
                    return new Builder();
                }

                public Builder clear() {
                    super.clear();
                    name_ = "";
                    bitField0_ = (bitField0_ & ~0x00000001);
                    type_ = com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType.BENZ;
                    bitField0_ = (bitField0_ & ~0x00000002);
                    return this;
                }

                public Builder clone() {
                    return create().mergeFrom(buildPartial());
                }

                public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                    return com.lyncc.netty.codec.protobuf.demo.RichManProto.internal_static_netty_RichMan_Car_descriptor;
                }

                public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car getDefaultInstanceForType() {
                    return com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.getDefaultInstance();
                }

                public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car build() {
                    com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car buildPartial() {
                    com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car result = new com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car(
                            this);
                    int from_bitField0_ = bitField0_;
                    int to_bitField0_ = 0;
                    if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                        to_bitField0_ |= 0x00000001;
                    }
                    result.name_ = name_;
                    if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                        to_bitField0_ |= 0x00000002;
                    }
                    result.type_ = type_;
                    result.bitField0_ = to_bitField0_;
                    onBuilt();
                    return result;
                }

                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car) {
                        return mergeFrom((com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car other) {
                    if (other == com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.getDefaultInstance())
                        return this;
                    if (other.hasName()) {
                        bitField0_ |= 0x00000001;
                        name_ = other.name_;
                        onChanged();
                    }
                    if (other.hasType()) {
                        setType(other.getType());
                    }
                    this.mergeUnknownFields(other.getUnknownFields());
                    return this;
                }

                public final boolean isInitialized() {
                    if (!hasName()) {

                        return false;
                    }
                    return true;
                }

                public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                    com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car) e
                                .getUnfinishedMessage();
                        throw e;
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                private int bitField0_;

                private java.lang.Object name_ = "";

                /**
                 * <code>required string name = 1;</code>
                 */
                public boolean hasName() {
                    return ((bitField0_ & 0x00000001) == 0x00000001);
                }

                /**
                 * <code>required string name = 1;</code>
                 */
                public java.lang.String getName() {
                    java.lang.Object ref = name_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            name_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }

                /**
                 * <code>required string name = 1;</code>
                 */
                public com.google.protobuf.ByteString getNameBytes() {
                    java.lang.Object ref = name_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                                .copyFromUtf8((java.lang.String) ref);
                        name_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>required string name = 1;</code>
                 */
                public Builder setName(java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    name_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>required string name = 1;</code>
                 */
                public Builder clearName() {
                    bitField0_ = (bitField0_ & ~0x00000001);
                    name_ = getDefaultInstance().getName();
                    onChanged();
                    return this;
                }

                /**
                 * <code>required string name = 1;</code>
                 */
                public Builder setNameBytes(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    name_ = value;
                    onChanged();
                    return this;
                }

                private com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType type_ = com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType.BENZ;

                /**
                 * <code>optional .netty.RichMan.CarType type = 2 [default = BENZ];</code>
                 */
                public boolean hasType() {
                    return ((bitField0_ & 0x00000002) == 0x00000002);
                }

                /**
                 * <code>optional .netty.RichMan.CarType type = 2 [default = BENZ];</code>
                 */
                public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType getType() {
                    return type_;
                }

                /**
                 * <code>optional .netty.RichMan.CarType type = 2 [default = BENZ];</code>
                 */
                public Builder setType(com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000002;
                    type_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional .netty.RichMan.CarType type = 2 [default = BENZ];</code>
                 */
                public Builder clearType() {
                    bitField0_ = (bitField0_ & ~0x00000002);
                    type_ = com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarType.BENZ;
                    onChanged();
                    return this;
                }

                // @@protoc_insertion_point(builder_scope:netty.RichMan.Car)
            }

            static {
                defaultInstance = new Car(true);
                defaultInstance.initFields();
            }

            // @@protoc_insertion_point(class_scope:netty.RichMan.Car)
        }

        private int bitField0_;

        public static final int ID_FIELD_NUMBER = 1;

        private int id_;

        /**
         * <code>required int32 id = 1;</code>
         */
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        public static final int NAME_FIELD_NUMBER = 2;

        private java.lang.Object name_;

        /**
         * <code>required string name = 2;</code>
         */
        public boolean hasName() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    name_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string name = 2;</code>
         */
        public com.google.protobuf.ByteString getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int EMAIL_FIELD_NUMBER = 3;

        private java.lang.Object email_;

        /**
         * <code>optional string email = 3;</code>
         */
        public boolean hasEmail() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string email = 3;</code>
         */
        public java.lang.String getEmail() {
            java.lang.Object ref = email_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    email_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string email = 3;</code>
         */
        public com.google.protobuf.ByteString getEmailBytes() {
            java.lang.Object ref = email_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                email_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CARS_FIELD_NUMBER = 4;

        private java.util.List<com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car> cars_;

        /**
         * <code>repeated .netty.RichMan.Car cars = 4;</code>
         */
        public java.util.List<com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car> getCarsList() {
            return cars_;
        }

        /**
         * <code>repeated .netty.RichMan.Car cars = 4;</code>
         */
        public java.util.List<? extends com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarOrBuilder> getCarsOrBuilderList() {
            return cars_;
        }

        /**
         * <code>repeated .netty.RichMan.Car cars = 4;</code>
         */
        public int getCarsCount() {
            return cars_.size();
        }

        /**
         * <code>repeated .netty.RichMan.Car cars = 4;</code>
         */
        public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car getCars(int index) {
            return cars_.get(index);
        }

        /**
         * <code>repeated .netty.RichMan.Car cars = 4;</code>
         */
        public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarOrBuilder getCarsOrBuilder(int index) {
            return cars_.get(index);
        }

        private void initFields() {
            id_ = 0;
            name_ = "";
            email_ = "";
            cars_ = java.util.Collections.emptyList();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            for (int i = 0; i < getCarsCount(); i++) {
                if (!getCars(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, id_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getNameBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getEmailBytes());
            }
            for (int i = 0; i < cars_.size(); i++) {
                output.writeMessage(4, cars_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getNameBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getEmailBytes());
            }
            for (int i = 0; i < cars_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, cars_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan parseFrom(
                com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan parseFrom(
                com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan parseDelimitedFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code netty.RichMan}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.RichMan)
                com.lyncc.netty.codec.protobuf.demo.RichManProto.RichManOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.lyncc.netty.codec.protobuf.demo.RichManProto.internal_static_netty_RichMan_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.lyncc.netty.codec.protobuf.demo.RichManProto.internal_static_netty_RichMan_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.class,
                                com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Builder.class);
            }

            // Construct using
            // com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getCarsFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                id_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                email_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                if (carsBuilder_ == null) {
                    cars_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                } else {
                    carsBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.lyncc.netty.codec.protobuf.demo.RichManProto.internal_static_netty_RichMan_descriptor;
            }

            public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan getDefaultInstanceForType() {
                return com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.getDefaultInstance();
            }

            public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan build() {
                com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan buildPartial() {
                com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan result = new com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.id_ = id_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.name_ = name_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.email_ = email_;
                if (carsBuilder_ == null) {
                    if (((bitField0_ & 0x00000008) == 0x00000008)) {
                        cars_ = java.util.Collections.unmodifiableList(cars_);
                        bitField0_ = (bitField0_ & ~0x00000008);
                    }
                    result.cars_ = cars_;
                } else {
                    result.cars_ = carsBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan) {
                    return mergeFrom((com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan other) {
                if (other == com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.getDefaultInstance())
                    return this;
                if (other.hasId()) {
                    setId(other.getId());
                }
                if (other.hasName()) {
                    bitField0_ |= 0x00000002;
                    name_ = other.name_;
                    onChanged();
                }
                if (other.hasEmail()) {
                    bitField0_ |= 0x00000004;
                    email_ = other.email_;
                    onChanged();
                }
                if (carsBuilder_ == null) {
                    if (!other.cars_.isEmpty()) {
                        if (cars_.isEmpty()) {
                            cars_ = other.cars_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                        } else {
                            ensureCarsIsMutable();
                            cars_.addAll(other.cars_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.cars_.isEmpty()) {
                        if (carsBuilder_.isEmpty()) {
                            carsBuilder_.dispose();
                            carsBuilder_ = null;
                            cars_ = other.cars_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                            carsBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getCarsFieldBuilder()
                                    : null;
                        } else {
                            carsBuilder_.addAllMessages(other.cars_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasId()) {

                    return false;
                }
                if (!hasName()) {

                    return false;
                }
                for (int i = 0; i < getCarsCount(); i++) {
                    if (!getCars(i).isInitialized()) {

                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int id_;

            /**
             * <code>required int32 id = 1;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public Builder setId(int value) {
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <code>required string name = 2;</code>
             */
            public boolean hasName() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        name_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string name = 2;</code>
             */
            public com.google.protobuf.ByteString getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder setName(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000002);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder setNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object email_ = "";

            /**
             * <code>optional string email = 3;</code>
             */
            public boolean hasEmail() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string email = 3;</code>
             */
            public java.lang.String getEmail() {
                java.lang.Object ref = email_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        email_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string email = 3;</code>
             */
            public com.google.protobuf.ByteString getEmailBytes() {
                java.lang.Object ref = email_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    email_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string email = 3;</code>
             */
            public Builder setEmail(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                email_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string email = 3;</code>
             */
            public Builder clearEmail() {
                bitField0_ = (bitField0_ & ~0x00000004);
                email_ = getDefaultInstance().getEmail();
                onChanged();
                return this;
            }

            /**
             * <code>optional string email = 3;</code>
             */
            public Builder setEmailBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                email_ = value;
                onChanged();
                return this;
            }

            private java.util.List<com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car> cars_ = java.util.Collections
                    .emptyList();

            private void ensureCarsIsMutable() {
                if (!((bitField0_ & 0x00000008) == 0x00000008)) {
                    cars_ = new java.util.ArrayList<com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car>(cars_);
                    bitField0_ |= 0x00000008;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car, com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder, com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarOrBuilder> carsBuilder_;

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public java.util.List<com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car> getCarsList() {
                if (carsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(cars_);
                } else {
                    return carsBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public int getCarsCount() {
                if (carsBuilder_ == null) {
                    return cars_.size();
                } else {
                    return carsBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car getCars(int index) {
                if (carsBuilder_ == null) {
                    return cars_.get(index);
                } else {
                    return carsBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public Builder setCars(int index, com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car value) {
                if (carsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCarsIsMutable();
                    cars_.set(index, value);
                    onChanged();
                } else {
                    carsBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public Builder setCars(int index,
                    com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder builderForValue) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    carsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public Builder addCars(com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car value) {
                if (carsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCarsIsMutable();
                    cars_.add(value);
                    onChanged();
                } else {
                    carsBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public Builder addCars(int index, com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car value) {
                if (carsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCarsIsMutable();
                    cars_.add(index, value);
                    onChanged();
                } else {
                    carsBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public Builder addCars(com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder builderForValue) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.add(builderForValue.build());
                    onChanged();
                } else {
                    carsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public Builder addCars(int index,
                    com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder builderForValue) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    carsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public Builder addAllCars(
                    java.lang.Iterable<? extends com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car> values) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(values, cars_);
                    onChanged();
                } else {
                    carsBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public Builder clearCars() {
                if (carsBuilder_ == null) {
                    cars_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                    onChanged();
                } else {
                    carsBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public Builder removeCars(int index) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.remove(index);
                    onChanged();
                } else {
                    carsBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder getCarsBuilder(int index) {
                return getCarsFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarOrBuilder getCarsOrBuilder(int index) {
                if (carsBuilder_ == null) {
                    return cars_.get(index);
                } else {
                    return carsBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public java.util.List<? extends com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarOrBuilder> getCarsOrBuilderList() {
                if (carsBuilder_ != null) {
                    return carsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(cars_);
                }
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder addCarsBuilder() {
                return getCarsFieldBuilder().addBuilder(
                        com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.getDefaultInstance());
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder addCarsBuilder(int index) {
                return getCarsFieldBuilder().addBuilder(index,
                        com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.getDefaultInstance());
            }

            /**
             * <code>repeated .netty.RichMan.Car cars = 4;</code>
             */
            public java.util.List<com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder> getCarsBuilderList() {
                return getCarsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car, com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder, com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarOrBuilder> getCarsFieldBuilder() {
                if (carsBuilder_ == null) {
                    carsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car, com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.Car.Builder, com.lyncc.netty.codec.protobuf.demo.RichManProto.RichMan.CarOrBuilder>(
                            cars_, ((bitField0_ & 0x00000008) == 0x00000008), getParentForChildren(), isClean());
                    cars_ = null;
                }
                return carsBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:netty.RichMan)
        }

        static {
            defaultInstance = new RichMan(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:netty.RichMan)
    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_netty_RichMan_descriptor;

    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_netty_RichMan_fieldAccessorTable;

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_netty_RichMan_Car_descriptor;

    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_netty_RichMan_Car_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\rRichMan.proto\022\005netty\"\322\001\n\007RichMan\022\n\n\002id"
                + "\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\r\n\005email\030\003 \001(\t\022 \n\004c"
                + "ars\030\004 \003(\0132\022.netty.RichMan.Car\032?\n\003Car\022\014\n\004"
                + "name\030\001 \002(\t\022*\n\004type\030\002 \001(\0162\026.netty.RichMan"
                + ".CarType:\004BENZ\";\n\007CarType\022\010\n\004AUDI\020\000\022\010\n\004B"
                + "ENZ\020\001\022\017\n\013LAMBORGHINI\020\002\022\013\n\007DASAUTO\020\003B3\n#c"
                + "om.lyncc.netty.codec.protobuf.demoB\014Rich" + "ManProto" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_netty_RichMan_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_netty_RichMan_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_netty_RichMan_descriptor, new java.lang.String[] { "Id", "Name", "Email", "Cars", });
        internal_static_netty_RichMan_Car_descriptor = internal_static_netty_RichMan_descriptor.getNestedTypes().get(0);
        internal_static_netty_RichMan_Car_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_netty_RichMan_Car_descriptor, new java.lang.String[] { "Name", "Type", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
